Array create chestunam


In [ ]:
import numpy as np
print(np.array([10,20]))

[10 20]


range tho array


In [ ]:
print(np.arange(10,20,2))

[10 12 14 16 18]


zeroes or ones tho or oka num tho array


In [ ]:
print(np.zeros(2))
print(np.ones(3))
print(np.full((2,1) ,5.5))

[0. 0.]
[1. 1. 1.]
[[5.5]
 [5.5]]


diff types of arrays


In [ ]:
arr_1d=np.array([1,2,3])
arr_2D=np.array([[1,2,3],[2,3,4]])
arr_3D=np.zeros([2,3,1])
arr_4D=np.ones([2,3,4,5])
print(arr_1d)
print(arr_2D)
print(arr_3D)
print(arr_4D)

[1 2 3]
[[1 2 3]
 [2 3 4]]
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]
[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]


identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Equally spaced values


In [ ]:
np.linspace(0,10,9) #9 anedi enni values kavali equal space tho


array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
np.random.rand(8)

array([0.11024557, 0.09960585, 0.7169704 , 0.86158761, 0.03426883,
       0.49527352, 0.59660724, 0.04090676])

In [ ]:
arr=np.array([[1,2,3],[2,3,4]],dtype=np.float32)
print(arr.size)
print(arr.dtype)
print(arr.shape)
print(arr.itemsize)
print(arr.ndim)

6
float32
(2, 3)
4
2


Assignment qs practice


In [ ]:
print(np.zeros([2,3,4]))#3D matrix

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
np.eye(4)#4x4 identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(np.random.randint(1,50,10))

[ 4 21 16  2 44 43  6 45 33 16]


In [ ]:
array=np.full((2,5),5)
print(array.shape)
print(array)

(2, 5)
[[5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
print(np.linspace(0,30,6))

[ 0.  6. 12. 18. 24. 30.]


In [ ]:
arr=np.arange(1,21)
print(arr[:10])#slicing [Create an array from 1–20 and print the first 10 elements.]
print([arr[-5:]])#last 5 elements
print(arr[::-1])#reverse array

[ 1  2  3  4  5  6  7  8  9 10]
[array([16, 17, 18, 19, 20])]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
arr=np.array([[1,2,3],
 [3,4,5],
  [6,7,8]])
print(arr[1])#print second row
print(arr[:,2])#print third column

[3 4 5]
[3 5 8]


In [ ]:
arr=np.arange(1,13)
print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(arr.flatten())#2d -1d

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
print(arr>10)#boolean indexing
print(arr[arr % 2 == 0])
print(arr[[0,2]])#fancy indexing arr.T also there for transpose


[[False False False]
 [False False False]
 [False False False]]
[2 4 6 8]
[[1 2 3]
 [6 7 8]]


In [ ]:
print(arr[:, ::-1])#reverse column


[[3 2 1]
 [5 4 3]
 [8 7 6]]


In [ ]:
arr = np.arange(1,26).reshape(5,5)

print(arr.sum(axis=0))#col wise
print(arr.sum(axis=1))#row wise
print(arr.max())

[55 60 65 70 75]
[ 15  40  65  90 115]
25


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [ ]:
a=np.array([1,2,3])
print(a*5)

[ 5 10 15]


In [ ]:
print(np.sqrt(16))
arr=np.array([2,3,4])
print(np.power(arr,3))
arr=np.array([-3,-4])
print(np.abs(arr))
arr=([10,20,30,40,50])
print(np.mean(arr))
print(np.median(arr))#std var also
arr=np.array([12,13,14,15,16])
print(np.max(arr))
print(np.argmax(arr))#return index same for min
print(arr[arr>12])#print cheyali ante


4.0
[ 8 27 64]
[3 4]
30.0
30.0
16
4
[13 14 15 16]


In [ ]:
import numpy as np

a = np.array([
    [1],
    [2],
    [3]
])
#broadcasting arrays
b = np.array([10,20,30])

print(a + b)

In [ ]:
import numpy as np

# Original Array
arr = np.array([12, 25, 37, 48, 59, 60, 71, 82, 93, 100])

print("Original Array:")
print(arr)

# 1. Mean
print("\n1. Mean:")
print(np.mean(arr))

# 2. Median
print("\n2. Median:")
print(np.median(arr))

# 3. Standard Deviation
print("\n3. Standard Deviation:")
print(np.std(arr))

# 4. Variance
print("\n4. Variance:")
print(np.var(arr))

# 5. Even Numbers
print("\n5. Even Numbers:")
print(arr[arr % 2 == 0])

# 6. Odd Numbers
print("\n6. Odd Numbers:")
print(arr[arr % 2 != 0])

# 7. Numbers Greater Than Mean
mean = np.mean(arr)
print("\n7. Numbers Greater Than Mean:")
print(arr[arr > mean])

# 8. Replace Odd Numbers with -1
new_arr = arr.copy()
new_arr[new_arr % 2 != 0] = -1

print("\n8. Replace Odd Numbers with -1:")
print(new_arr)

# 9. Index of Maximum Value
print("\n9. Index of Maximum Value:")
print(np.argmax(arr))

# 10. Min-Max Normalization
normalized = (arr - arr.min()) / (arr.max() - arr.min())

print("\n10. Min-Max Normalization:")
print(normalized)

In [ ]:
import numpy as np

# Original Array
arr = np.array([5, 10, 15, 20, 25, 30])

print("Original Array:")
print(arr)

# 1. Sum
print("\n1. Sum:")
print(np.sum(arr))

# 2. Product
print("\n2. Product:")
print(np.prod(arr))

# 3. Average (Mean)
print("\n3. Average (Mean):")
print(np.mean(arr))

# 4. Square of Every Element
print("\n4. Square of Every Element:")
print(np.square(arr))

# 5. Cube Root of Every Element
print("\n5. Cube Root of Every Element:")
print(np.cbrt(arr))

# 6. Elements Divisible by 5
print("\n6. Elements Divisible by 5:")
print(arr[arr % 5 == 0])

# 7. Replace Values Greater Than 20 with 0
new_arr = arr.copy()
new_arr[new_arr > 20] = 0

print("\n7. Replace Values Greater Than 20 with 0:")
print(new_arr)

# 8. Round Values to 2 Decimal Places
decimal_arr = np.array([2.345, 5.678, 9.876])

print("\n8. Round to 2 Decimal Places:")
print(np.round(decimal_arr, 2))

# 9. Exponential Values
exp_arr = np.array([1, 2, 3])

print("\n9. Exponential Values:")
print(np.exp(exp_arr))

# 10. Log Base 10
log_arr = np.array([1, 10, 100, 1000])

print("\n10. Log Base 10:")
print(np.log10(log_arr))

In [ ]:
import numpy as np

# Original Array
arr = np.array([5, 10, 15, 20, 25, 30])

print("Original Array:")
print(arr)

# 1. Sum
print("\n1. Sum:")
print(np.sum(arr))

# 2. Product
print("\n2. Product:")
print(np.prod(arr))

# 3. Average (Mean)
print("\n3. Average (Mean):")
print(np.mean(arr))

# 4. Square of Every Element
print("\n4. Square of Every Element:")
print(np.square(arr))

# 5. Cube Root of Every Element
print("\n5. Cube Root of Every Element:")
print(np.cbrt(arr))

# 6. Elements Divisible by 5
print("\n6. Elements Divisible by 5:")
print(arr[arr % 5 == 0])

# 7. Replace Values Greater Than 20 with 0
new_arr = arr.copy()
new_arr[new_arr > 20] = 0

print("\n7. Replace Values Greater Than 20 with 0:")
print(new_arr)

# 8. Round Values to 2 Decimal Places
decimal_arr = np.array([2.345, 5.678, 9.876])

print("\n8. Round to 2 Decimal Places:")
print(np.round(decimal_arr, 2))

# 9. Exponential Values
exp_arr = np.array([1, 2, 3])

print("\n9. Exponential Values:")
print(np.exp(exp_arr))

# 10. Log Base 10
log_arr = np.array([1, 10, 100, 1000])

print("\n10. Log Base 10:")
print(np.log10(log_arr))

In [ ]:
print(arr[(arr > 20) & (arr < 50)])
print(arr[(arr < 20) | (arr > 40)])
arr = np.array([10,20,30,40,50])

result = np.where(arr > 30, 1, 0)

print(result)
arr = np.array([5,15,25,35,45])
print(np.clip(arr,10,30))#min range ki max range ki dhani adjust cheydam

arr = np.array([1,2,2,3,3,3,4,5,5])
print(np.unique(arr))

arr = np.array([0,1,2,0,3,0,4])
print(np.count_nonzero(arr))

arr = np.array([True, True, False])
print(np.any(arr))# if one element is true it returns true
print(np.all(arr))#If all elements are True, it returns True.Otherwise False.

[]
[12 13 14 15 16]
[0 0 0 1 1]
[10 15 25 30 30]
[1 2 3 4 5]
4
True
False


In [ ]:
import numpy as np

# 4×4 Matrix
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

print("Original Matrix:")
print(arr)

# 1. Sum of each row
print("\n1. Sum of each row:")
print(np.sum(arr, axis=1))

# 2. Sum of each column
print("\n2. Sum of each column:")
print(np.sum(arr, axis=0))

# 3. Mean of each row
print("\n3. Mean of each row:")
print(np.mean(arr, axis=1))

# 4. Mean of each column
print("\n4. Mean of each column:")
print(np.mean(arr, axis=0))

# 5. Maximum value of each row
print("\n5. Maximum value of each row:")
print(np.max(arr, axis=1))

# 6. Minimum value of each column
print("\n6. Minimum value of each column:")
print(np.min(arr, axis=0))

# --------------------------------------------------

arr2 = np.array([10, 25, 35, 45, 55, 65, 75])

print("\nArray:")
print(arr2)

# 7. Filter numbers greater than 50
print("\n7. Numbers greater than 50:")
print(arr2[arr2 > 50])

# 8. Filter numbers between 20 and 60
print("\n8. Numbers between 20 and 60:")
print(arr2[(arr2 >= 20) & (arr2 <= 60)])

# 9. Replace values less than 30 with 0
new_arr = arr2.copy()
new_arr[new_arr < 30] = 0

print("\n9. Replace values less than 30 with 0:")
print(new_arr)

# 10. np.where()
print("\n10. Replace values > 50 with 1 else 0:")
print(np.where(arr2 > 50, 1, 0))

# --------------------------------------------------

arr3 = np.array([1,2,2,3,4,4,5,5,5])

print("\n11. Unique Values:")
print(np.unique(arr3))

# --------------------------------------------------

arr4 = np.array([0,5,0,10,15,0,20])

print("\n12. Count Non-Zero Elements:")
print(np.count_nonzero(arr4))

# --------------------------------------------------

print("\n13. Any value greater than 90?")
print(np.any(arr2 > 90))

print("\n14. All values greater than 10?")
print(np.all(arr2 > 10))

# --------------------------------------------------

arr5 = np.array([5,15,25,35,45])

print("\n15. Clip values between 10 and 30:")
print(np.clip(arr5, 10, 30))

In [ ]:
import numpy as np

# ==========================
# 1. Sort in Ascending Order
# ==========================
arr = np.array([45, 12, 78, 23, 56])

print("Original Array:")
print(arr)

print("\n1. Ascending Sort:")
print(np.sort(arr))

# ==========================
# 2. Sort in Descending Order
# ==========================
print("\n2. Descending Sort:")
print(np.sort(arr)[::-1])

# ==========================
# 3. Argsort
# ==========================
print("\n3. Argsort:")
print(np.argsort(arr))

# ==========================
# 4. Concatenate
# ==========================
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\n4. Concatenate:")
print(np.concatenate((a, b)))

# ==========================
# 5. Vertical Stack
# ==========================
print("\n5. Vertical Stack:")
print(np.vstack((a, b)))

# ==========================
# 6. Horizontal Stack
# ==========================
print("\n6. Horizontal Stack:")
print(np.hstack((a, b)))

# ==========================
# 7. Column Stack
# ==========================
print("\n7. Column Stack:")
print(np.column_stack((a, b)))

# ==========================
# 8. Split Array
# ==========================
arr2 = np.array([10, 20, 30, 40, 50, 60])

print("\n8. Split into 3 Parts:")
print(np.split(arr2, 3))

# ==========================
# 9. Append
# ==========================
arr3 = np.array([10, 20, 30])

print("\n9. Append 70:")
print(np.append(arr3, 70))

# ==========================
# 10. Insert
# ==========================
print("\n10. Insert 15 at Index 1:")
print(np.insert(arr3, 1, 15))

# ==========================
# 11. Delete
# ==========================
arr4 = np.array([10, 20, 30, 40])

print("\n11. Delete Element at Index 2:")
print(np.delete(arr4, 2))

# ==========================
# 12. Copy
# ==========================
original = np.array([10, 20, 30])

copy_arr = original.copy()
copy_arr[0] = 100

print("\n12. Copy Example")
print("Original :", original)
print("Copy     :", copy_arr)

# ==========================
# 13. View
# ==========================
original2 = np.array([10, 20, 30])

view_arr = original2.view()
view_arr[0] = 100

print("\n13. View Example")
print("Original :", original2)
print("View     :", view_arr)

# ==========================
# 14. Vertical Split
# ==========================
matrix1 = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

print("\n14. Vertical Split:")
print(np.vsplit(matrix1, 2))

# ==========================
# 15. Horizontal Split
# ==========================
matrix2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print("\n15. Horizontal Split:")
print(np.hsplit(matrix2, 2))

Original Array:
[45 12 78 23 56]

1. Ascending Sort:
[12 23 45 56 78]

2. Descending Sort:
[78 56 45 23 12]

3. Argsort:
[1 3 0 4 2]

4. Concatenate:
[1 2 3 4 5 6]

5. Vertical Stack:
[[1 2 3]
 [4 5 6]]

6. Horizontal Stack:
[1 2 3 4 5 6]

7. Column Stack:
[[1 4]
 [2 5]
 [3 6]]

8. Split into 3 Parts:
[array([10, 20]), array([30, 40]), array([50, 60])]

9. Append 70:
[10 20 30 70]

10. Insert 15 at Index 1:
[10 15 20 30]

11. Delete Element at Index 2:
[10 20 40]

12. Copy Example
Original : [10 20 30]
Copy     : [100  20  30]

13. View Example
Original : [100  20  30]
View     : [100  20  30]

14. Vertical Split:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]

15. Horizontal Split:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [ ]:
import numpy as np

# ==========================================
# DAY 6 - ALL PRACTICE QUESTIONS IN ONE CODE
# ==========================================

# 1. Generate 5 random decimal numbers
print("1. Random Decimal Numbers:")
print(np.random.rand(5))

# ------------------------------------------

# 2. Generate 10 random integers between 1 and 100
print("\n2. Random Integers:")
print(np.random.randint(1, 101, 10))

# ------------------------------------------

# 3. Select 3 random elements
arr = np.array([10, 20, 30, 40, 50])

print("\n3. Random Choice:")
print(np.random.choice(arr, 3))

# ------------------------------------------

# 4. Shuffle an array
arr2 = np.array([1, 2, 3, 4, 5])

np.random.shuffle(arr2)

print("\n4. Shuffled Array:")
print(arr2)

# ------------------------------------------

# 5. Random Seed
np.random.seed(42)

print("\n5. Seed(42) Random Integers:")
print(np.random.randint(1, 100, 5))

# ==========================================
# LINEAR ALGEBRA
# ==========================================

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# 6. Matrix Addition
print("\n6. Matrix Addition:")
print(A + B)

# ------------------------------------------

# 7. Matrix Subtraction
print("\n7. Matrix Subtraction:")
print(A - B)

# ------------------------------------------

# 8. Matrix Multiplication
print("\n8. Matrix Multiplication:")
print(np.matmul(A, B))

# OR
# print(A @ B)

# ------------------------------------------

# 9. Dot Product
a = np.array([2, 3, 4])
b = np.array([5, 6, 7])

print("\n9. Dot Product:")
print(np.dot(a, b))

# ------------------------------------------

# 10. Transpose
print("\n10. Transpose:")
print(A.T)

# ------------------------------------------

# 11. Inverse
C = np.array([
    [4, 7],
    [2, 6]
])

print("\n11. Inverse:")
print(np.linalg.inv(C))

# ------------------------------------------

# 12. Determinant
print("\n12. Determinant:")
print(np.linalg.det(C))

# ------------------------------------------

# 13. Eigenvalues & Eigenvectors
values, vectors = np.linalg.eig(C)

print("\n13. Eigenvalues:")
print(values)

print("\nEigenvectors:")
print(vectors)

# ------------------------------------------

# 14. Norm
d = np.array([6, 8])

print("\n14. Norm:")
print(np.linalg.norm(d))

# ------------------------------------------

# 15. Feature Matrix × Weight Vector

X = np.array([
    [20, 70],
    [25, 80],
    [30, 90]
])

weights = np.array([0.4, 0.6])

prediction = X @ weights

print("\n15. Feature Matrix × Weight Vector:")
print(prediction)

1. Random Decimal Numbers:
[0.00121496 0.18270929 0.08870825 0.80402367 0.79099446]

2. Random Integers:
[50 81 60 44 91 14 75 24 57 73]

3. Random Choice:
[30 10 30]

4. Shuffled Array:
[4 5 2 3 1]

5. Seed(42) Random Integers:
[52 93 15 72 61]

6. Matrix Addition:
[[ 6  8]
 [10 12]]

7. Matrix Subtraction:
[[-4 -4]
 [-4 -4]]

8. Matrix Multiplication:
[[19 22]
 [43 50]]

9. Dot Product:
56

10. Transpose:
[[1 3]
 [2 4]]

11. Inverse:
[[ 0.6 -0.7]
 [-0.2  0.4]]

12. Determinant:
10.000000000000002

13. Eigenvalues:
[1.12701665 8.87298335]

Eigenvectors:
[[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]

14. Norm:
10.0

15. Feature Matrix × Weight Vector:
[50. 58. 66.]


In [ ]:
import numpy as np

# Dataset
data = np.array([
    [23, 45000],
    [25, 50000],
    [30, 60000],
    [35, 70000],
    [40, 80000],
    [28, 55000],
    [32, 65000],
    [26, 52000],
    [45, 90000],
    [38, 75000]
])

print("Original Dataset:")
print(data)

# 1. Print only the Age column
print("\n1. Age Column:")
print(data[:, 0])

# 2. Print only the Salary column
print("\n2. Salary Column:")
print(data[:, 1])

# 3. Print the first 5 rows
print("\n3. First 5 Rows:")
print(data[:5])

# 4. Print the last 3 rows
print("\n4. Last 3 Rows:")
print(data[-3:])

# 5. Print employees whose age is greater than 30
print("\n5. Employees with Age > 30:")
print(data[data[:, 0] > 30])

# 6. Print employees whose salary is greater than 60000
print("\n6. Employees with Salary > 60000:")
print(data[data[:, 1] > 60000])

# 7. Print employees whose age is between 25 and 35
print("\n7. Employees with Age Between 25 and 35:")
print(data[(data[:, 0] >= 25) & (data[:, 0] <= 35)])

# 8. Find the average age
print("\n8. Average Age:")
print(np.mean(data[:, 0]))

# 9. Find the average salary
print("\n9. Average Salary:")
print(np.mean(data[:, 1]))

# 10. Find the maximum salary
print("\n10. Maximum Salary:")
print(np.max(data[:, 1]))

Original Dataset:
[[   23 45000]
 [   25 50000]
 [   30 60000]
 [   35 70000]
 [   40 80000]
 [   28 55000]
 [   32 65000]
 [   26 52000]
 [   45 90000]
 [   38 75000]]

1. Age Column:
[23 25 30 35 40 28 32 26 45 38]

2. Salary Column:
[45000 50000 60000 70000 80000 55000 65000 52000 90000 75000]

3. First 5 Rows:
[[   23 45000]
 [   25 50000]
 [   30 60000]
 [   35 70000]
 [   40 80000]]

4. Last 3 Rows:
[[   26 52000]
 [   45 90000]
 [   38 75000]]

5. Employees with Age > 30:
[[   35 70000]
 [   40 80000]
 [   32 65000]
 [   45 90000]
 [   38 75000]]

6. Employees with Salary > 60000:
[[   35 70000]
 [   40 80000]
 [   32 65000]
 [   45 90000]
 [   38 75000]]

7. Employees with Age Between 25 and 35:
[[   25 50000]
 [   30 60000]
 [   35 70000]
 [   28 55000]
 [   32 65000]
 [   26 52000]]

8. Average Age:
32.2

9. Average Salary:
64200.0

10. Maximum Salary:
90000


In [16]:
import numpy as np

# Dataset
data = np.array([
    [23, 45000],
    [25, 50000],
    [30, 60000],
    [35, 70000],
    [40, 80000],
    [28, 55000],
    [32, 65000],
    [26, 52000],
    [45, 90000],
    [38, 75000]
])

print("Original Dataset:")
print(data)

# 11. Minimum Salary
print("\n11. Minimum Salary:")
print(np.min(data[:, 1]))

# 12. Employee Having Maximum Salary
print("\n12. Employee with Maximum Salary:")
max_salary_index = np.argmax(data[:, 1])
print(data[max_salary_index])

# 13. Employee Having Minimum Age
print("\n13. Employee with Minimum Age:")
min_age_index = np.argmin(data[:, 0])
print(data[min_age_index])

# 14. Count Employees with Salary > 60000
print("\n14. Count of Employees with Salary > 60000:")
count = np.count_nonzero(data[:, 1] > 60000)
print(count)

# 15. Replace Salaries Greater Than 80000 with 80000
print("\n15. Replace Salaries > 80000 with 80000:")
new_data = data.copy()
new_data[new_data[:, 1] > 80000, 1] = 80000
print(new_data)

# 16. Min-Max Normalize Salary Column
print("\n16. Normalized Salary:")
salary = data[:, 1]
normalized_salary = (salary - salary.min()) / (salary.max() - salary.min())
print(normalized_salary)

# 17. Sort Employees by Salary
print("\n17. Employees Sorted by Salary:")
salary_sorted = data[np.argsort(data[:, 1])]
print(salary_sorted)

# 18. Sort Employees by Age
print("\n18. Employees Sorted by Age:")
age_sorted = data[np.argsort(data[:, 0])]
print(age_sorted)

# 19. Index of Highest Salary
print("\n19. Index of Highest Salary:")
print(np.argmax(data[:, 1]))

# 20. Index of Youngest Employee
print("\n20. Index of Youngest Employee:")
print(np.argmin(data[:, 0]))




Original Dataset:
[[   23 45000]
 [   25 50000]
 [   30 60000]
 [   35 70000]
 [   40 80000]
 [   28 55000]
 [   32 65000]
 [   26 52000]
 [   45 90000]
 [   38 75000]]

11. Minimum Salary:
45000

12. Employee with Maximum Salary:
[   45 90000]

13. Employee with Minimum Age:
[   23 45000]

14. Count of Employees with Salary > 60000:
5

15. Replace Salaries > 80000 with 80000:
[[   23 45000]
 [   25 50000]
 [   30 60000]
 [   35 70000]
 [   40 80000]
 [   28 55000]
 [   32 65000]
 [   26 52000]
 [   45 80000]
 [   38 75000]]

16. Normalized Salary:
[0.         0.11111111 0.33333333 0.55555556 0.77777778 0.22222222
 0.44444444 0.15555556 1.         0.66666667]

17. Employees Sorted by Salary:
[[   23 45000]
 [   25 50000]
 [   26 52000]
 [   28 55000]
 [   30 60000]
 [   32 65000]
 [   35 70000]
 [   38 75000]
 [   40 80000]
 [   45 90000]]

18. Employees Sorted by Age:
[[   23 45000]
 [   25 50000]
 [   26 52000]
 [   28 55000]
 [   30 60000]
 [   32 65000]
 [   35 70000]
 [   38 75000

In [19]:
import numpy as np

# Dataset
data = np.array([
    [23, 45000],
    [25, 50000],
    [30, 60000],
    [35, 70000],
    [40, 80000],
    [28, 55000],
    [32, 65000],
    [26, 52000],
    [45, 90000],
    [38, 75000]
])

print("Original Dataset:")
print(data)

# ----------------------------------------
# 21. Add a bonus of ₹5000 to every salary
# ----------------------------------------
bonus_data = data.copy()
bonus_data[:, 1] += 5000

print("\n21. Salary + ₹5000 Bonus:")
print(bonus_data)

# ----------------------------------------
# 22. Increase salary by 10%
# ----------------------------------------
increase_data = data.copy()
increase_data[:, 1] = increase_data[:, 1] * 1.10

print("\n22. Salary Increased by 10%:")
print(increase_data)

# ----------------------------------------
# 23. Create Tax Column (10% of Salary)
# ----------------------------------------
tax = data[:, 1] * 0.10

print("\n23. Tax Column:")
print(tax)

# ----------------------------------------
# 24. Append Tax Column to Dataset
# ----------------------------------------
new_dataset = np.column_stack((data, tax))

print("\n24. Dataset with Tax Column:")
print(new_dataset)

# ----------------------------------------
# 25. Total Salary Paid
# ----------------------------------------
print("\n25. Total Salary Paid:")
print(np.sum(data[:, 1]))

# ----------------------------------------
# 26. Standard Deviation of Salary
# ----------------------------------------
print("\n26. Standard Deviation:")
print(np.std(data[:, 1]))

# ----------------------------------------
# 27. Variance of Salary
# ----------------------------------------
print("\n27. Variance:")
print(np.var(data[:, 1]))

# ----------------------------------------
# 28. Employees Earning Above Average Salary
# ----------------------------------------
avg_salary = np.mean(data[:, 1])

print("\n28. Employees Earning Above Average Salary:")
print(data[data[:, 1] > avg_salary])

# ----------------------------------------
# 29. Shuffle Dataset
# ----------------------------------------
shuffle_data = data.copy()
np.random.shuffle(shuffle_data)

print("\n29. Shuffled Dataset:")
print(shuffle_data)

# ----------------------------------------
# 30. Randomly Select 5 Employees
# ----------------------------------------
random_employees = data[np.random.choice(data.shape[0], 5, replace=False)]

print("\n30. Randomly Selected 5 Employees:")
print(random_employees)

# ----------------------------------------
# 31. Set age to 30 for employees older than 30
# ----------------------------------------


Original Dataset:
[[   23 45000]
 [   25 50000]
 [   30 60000]
 [   35 70000]
 [   40 80000]
 [   28 55000]
 [   32 65000]
 [   26 52000]
 [   45 90000]
 [   38 75000]]

21. Salary + ₹5000 Bonus:
[[   23 50000]
 [   25 55000]
 [   30 65000]
 [   35 75000]
 [   40 85000]
 [   28 60000]
 [   32 70000]
 [   26 57000]
 [   45 95000]
 [   38 80000]]

22. Salary Increased by 10%:
[[   23 49500]
 [   25 55000]
 [   30 66000]
 [   35 77000]
 [   40 88000]
 [   28 60500]
 [   32 71500]
 [   26 57200]
 [   45 99000]
 [   38 82500]]

23. Tax Column:
[4500. 5000. 6000. 7000. 8000. 5500. 6500. 5200. 9000. 7500.]

24. Dataset with Tax Column:
[[2.3e+01 4.5e+04 4.5e+03]
 [2.5e+01 5.0e+04 5.0e+03]
 [3.0e+01 6.0e+04 6.0e+03]
 [3.5e+01 7.0e+04 7.0e+03]
 [4.0e+01 8.0e+04 8.0e+03]
 [2.8e+01 5.5e+04 5.5e+03]
 [3.2e+01 6.5e+04 6.5e+03]
 [2.6e+01 5.2e+04 5.2e+03]
 [4.5e+01 9.0e+04 9.0e+03]
 [3.8e+01 7.5e+04 7.5e+03]]

25. Total Salary Paid:
642000

26. Standard Deviation:
13738.995596476476

27. Variance:
18

In [20]:
import numpy as np

# Dataset
data = np.array([
    [23, 45000],
    [25, 50000],
    [30, 60000],
    [35, 70000],
    [40, 80000],
    [28, 55000],
    [32, 65000],
    [26, 52000],
    [45, 90000],
    [38, 75000]
])

print("Original Dataset:")
print(data)

# ---------------------------------------
# 31. Replace every age below 30 with 30
# ---------------------------------------
age_data = data.copy()
age_data[age_data[:, 0] < 30, 0] = 30

print("\n31. Replace Age < 30 with 30:")
print(age_data)

# ---------------------------------------
# 32. Clip salaries between 50000 and 80000
# ---------------------------------------
clip_data = data.copy()
clip_data[:, 1] = np.clip(clip_data[:, 1], 50000, 80000)

print("\n32. Clip Salaries (50000 - 80000):")
print(clip_data)

# ---------------------------------------
# 33. Check if any employee earns > 85000
# ---------------------------------------
print("\n33. Any Salary > 85000?")
print(np.any(data[:, 1] > 85000))

# ---------------------------------------
# 34. Check if all employees earn > 40000
# ---------------------------------------
print("\n34. All Salaries > 40000?")
print(np.all(data[:, 1] > 40000))

# ---------------------------------------
# 35. Find Unique Ages
# ---------------------------------------
print("\n35. Unique Ages:")
print(np.unique(data[:, 0]))

# ---------------------------------------
# 36. Count Employees Older Than 30
# ---------------------------------------
print("\n36. Employees Older Than 30:")
print(np.count_nonzero(data[:, 0] > 30))

# ---------------------------------------
# 37. Reshape Salary into (10,1)
# ---------------------------------------
salary = data[:, 1].reshape(10, 1)

print("\n37. Salary Reshaped (10x1):")
print(salary)

# ---------------------------------------
# 38. Flatten Salary Array
# ---------------------------------------
print("\n38. Flatten Salary:")
print(salary.flatten())

# ---------------------------------------
# 39. Dot Product of Salary and Weight Vector
# ---------------------------------------
weights = np.ones(10)

dot_product = np.dot(data[:, 1], weights)

print("\n39. Dot Product:")
print(dot_product)

# ---------------------------------------
# 40. Mean Salary Using Two Methods
# ---------------------------------------
mean1 = np.mean(data[:, 1])
mean2 = data[:, 1].mean()

print("\n40. Mean Using np.mean():")
print(mean1)

print("\nMean Using arr.mean():")
print(mean2)

print("\nAre Both Equal?")
print(mean1 == mean2)

Original Dataset:
[[   23 45000]
 [   25 50000]
 [   30 60000]
 [   35 70000]
 [   40 80000]
 [   28 55000]
 [   32 65000]
 [   26 52000]
 [   45 90000]
 [   38 75000]]

31. Replace Age < 30 with 30:
[[   30 45000]
 [   30 50000]
 [   30 60000]
 [   35 70000]
 [   40 80000]
 [   30 55000]
 [   32 65000]
 [   30 52000]
 [   45 90000]
 [   38 75000]]

32. Clip Salaries (50000 - 80000):
[[   23 50000]
 [   25 50000]
 [   30 60000]
 [   35 70000]
 [   40 80000]
 [   28 55000]
 [   32 65000]
 [   26 52000]
 [   45 80000]
 [   38 75000]]

33. Any Salary > 85000?
True

34. All Salaries > 40000?
True

35. Unique Ages:
[23 25 26 28 30 32 35 38 40 45]

36. Employees Older Than 30:
5

37. Salary Reshaped (10x1):
[[45000]
 [50000]
 [60000]
 [70000]
 [80000]
 [55000]
 [65000]
 [52000]
 [90000]
 [75000]]

38. Flatten Salary:
[45000 50000 60000 70000 80000 55000 65000 52000 90000 75000]

39. Dot Product:
642000.0

40. Mean Using np.mean():
64200.0

Mean Using arr.mean():
64200.0

Are Both Equal?
True